/**
 * bash 集成脚本模板。
 * 通过 `bind -x` 绑定 Ctrl+G，读取并替换 READLINE_LINE。
 * 需要 bash 4+（`bind -x` + READLINE_LINE/POINT 变量）。
 *
 * 实现细节说明：脚本内容以纯字符串拼接方式构造，避免与 JS 模板插值冲突。
 */
const LINES: string[] = [
  '# >>> WhatTheShell (wts) bash integration >>>',
  '# Generated by: wts shell-init bash',
  '# 安装: 在 ~/.bashrc 里加入:   eval "$(wts shell-init bash)"',
  '',
  '__wts_inline_widget() {',
  '  local current="$READLINE_LINE"',
  '  local intent=""',
  '',
  '  echo',
  '  if ! read -r -e -p "wts > " intent; then',
  '    return 0',
  '  fi',
  '  if [[ -z "$intent" ]]; then',
  '    return 0',
  '  fi',
  '',
  "  printf 'wts: thinking...\\r'",
  '',
  '  local tmpout tmperr rc',
  '  tmpout=$(mktemp 2>/dev/null) || return 1',
  '  tmperr=$(mktemp 2>/dev/null) || { rm -f "$tmpout"; return 1; }',
  '',
  '  command wts generate --inline --shell bash \\',
  '    --buffer "$current" \\',
  '    --history-file "${HISTFILE:-}" \\',
  '    -- "$intent" \\',
  '    >"$tmpout" 2>"$tmperr"',
  '  rc=$?',
  '',
  "  printf '\\r\\033[2K'",
  '',
  '  if (( rc == 0 )); then',
  '    READLINE_LINE=$(<"$tmpout")',
  '    READLINE_POINT=${#READLINE_LINE}',
  '  else',
  '    cat "$tmperr" >&2',
  '  fi',
  '',
  '  rm -f "$tmpout" "$tmperr"',
  '}',
  '',
  'bind -x \'"\\C-g":__wts_inline_widget\' 2>/dev/null',
  '# <<< WhatTheShell (wts) bash integration <<<',
  '',
];

export const BASH_INIT_SCRIPT = LINES.join('\n');
