/**
 * fish 集成脚本模板。
 *
 * fish 没有 bash 的 `bind -x` / zsh 的 ZLE widget，但提供:
 *   - `commandline`        读 / 写 / 光标定位当前命令行
 *   - `bind \cg FUNC`      绑定 Ctrl+G
 * 语义上与 zsh 的 `BUFFER=...` + `CURSOR=${#BUFFER}` 完全对得上。
 *
 * 安装路径：一般写到 ~/.config/fish/conf.d/wts.fish 就会在每个新 shell 里自动加载。
 */
const LINES: string[] = [
  '# >>> WhatTheShell (wts) fish integration >>>',
  '# Generated by: wts shell-init fish',
  '# Install: save this block as ~/.config/fish/conf.d/wts.fish',
  '',
  'function __wts_inline_widget',
  '    set -l current (commandline)',
  '    set -l intent',
  '',
  '    echo',
  "    read -P 'wts > ' intent",
  '    if test -z "$intent"',
  '        commandline -f repaint',
  '        return',
  '    end',
  '',
  "    printf 'wts: thinking...\\r'",
  '',
  '    set -l tmpout (mktemp 2>/dev/null)',
  '    set -l tmperr (mktemp 2>/dev/null)',
  '    if test -z "$tmpout" -o -z "$tmperr"',
  '        commandline -f repaint',
  '        return 1',
  '    end',
  '',
  '    command wts generate --inline --shell fish \\',
  '        --buffer "$current" \\',
  '        --history-file "$HISTFILE" \\',
  '        -- "$intent" >$tmpout 2>$tmperr',
  '    set -l rc $status',
  '',
  "    printf '\\r\\033[2K'",
  '',
  '    if test $rc -eq 0',
  '        set -l result (string collect < $tmpout)',
  '        if test -n "$result"',
  '            commandline -r -- $result',
  '            commandline -C (string length -- $result)',
  '        end',
  '    else',
  '        cat $tmperr >&2',
  '    end',
  '',
  '    rm -f $tmpout $tmperr',
  '    commandline -f repaint',
  'end',
  '',
  'bind \\cg __wts_inline_widget',
  '# <<< WhatTheShell (wts) fish integration <<<',
  '',
];

export const FISH_INIT_SCRIPT = LINES.join('\n');
