/**
 * PowerShell 集成脚本模板。
 *
 * 依赖 PSReadLine（Windows PowerShell 5.1 / PowerShell 7 默认预装）。
 * 通过 `Set-PSReadLineKeyHandler -Chord 'Ctrl+g'` 注册 Ctrl+G 处理函数。
 *
 * 输出脚本做了几件事提高兼容性：
 * 1. 所有注释和字符串都是 ASCII —— `Out-String | Add-Content -Path $PROFILE`
 *    在 PS 5.1 上会用系统 ANSI 写文件，中文经由 UTF8 → GBK 再读回 UTF-16 容易
 *    丢字节；纯 ASCII 就没这个风险。
 * 2. 不使用反引号续行 —— 反引号在 `Out-String` 的默认 `-Width 80` 截断下有风
 *    险，单行写完最稳。
 * 3. 调 wts 时用数组 splat；空 buffer 不传 --buffer，避免 PS 5.1 native 参数
 *    透传丢空串导致 commander 读不到 <description>。
 * 4. 调用 wts 期间临时把 `[Console]::OutputEncoding` 切到 UTF-8（不带 BOM），
 *    避免 PS 5.1 默认 CP936 把 Node 的 UTF-8 stdout/stderr 解成乱码；并用
 *    `2>&1 | ForEach-Object` 按 ErrorRecord 分流，绕开 PS 5.1 "native command
 *    写 stderr 就包 NativeCommandError" 的默认行为（即便 `2>$file` 也会触发）。
 *
 * 安装路径：追加到 $PROFILE（通常 Documents/PowerShell/Microsoft.PowerShell_profile.ps1）。
 */
const LINES: string[] = [
  '# >>> WhatTheShell (wts) PowerShell integration >>>',
  '# Generated by: wts shell-init powershell',
  '',
  'if (-not (Get-Module -ListAvailable -Name PSReadLine)) {',
  "    Write-Warning 'WhatTheShell: PSReadLine not found, Ctrl+G integration skipped'",
  '    return',
  '}',
  '',
  "Set-PSReadLineKeyHandler -Chord 'Ctrl+g' -BriefDescription 'WhatTheShell inline' -Description 'Generate shell command via AI and fill the current buffer' -ScriptBlock {",
  "    $line = ''",
  '    $cursor = 0',
  '    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)',
  "    if ($null -eq $line) { $line = '' }",
  '',
  "    Write-Host ''",
  '    Write-Host -NoNewline "[WhatTheShell] > " -ForegroundColor Cyan',
  '    $intent = Read-Host',
  '    if ([string]::IsNullOrWhiteSpace($intent)) {',
  '        [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()',
  '        return',
  '    }',
  '',
  "    Write-Host -NoNewline 'wts: thinking...'",
  '',
  '    # PS 5.1 default OutputEncoding is CP936 on zh-CN Windows, which mangles',
  "    # wts's UTF-8 output. Also, writing to stderr from a native command raises",
  '    # a NativeCommandError on top of whatever we print. Flipping to UTF-8 and',
  '    # routing 2>&1 through a pipeline sidesteps both.',
  '    $stdoutLines = [System.Collections.ArrayList]@()',
  '    $stderrLines = [System.Collections.ArrayList]@()',
  '    $rc = 1',
  '    $prevEnc = [Console]::OutputEncoding',
  '    $prevEAP = $ErrorActionPreference',
  "    $ErrorActionPreference = 'Continue'",
  '    try {',
  '        [Console]::OutputEncoding = New-Object System.Text.UTF8Encoding $false',
  "        $wtsArgs = [System.Collections.ArrayList]@('generate', '--inline', '--shell', 'powershell')",
  '        if ($line.Length -gt 0) {',
  "            [void]$wtsArgs.Add('--buffer')",
  '            [void]$wtsArgs.Add($line)',
  '        }',
  "        [void]$wtsArgs.Add('--')",
  '        [void]$wtsArgs.Add($intent)',
  '        & wts @wtsArgs 2>&1 | ForEach-Object {',
  '            if ($_ -is [System.Management.Automation.ErrorRecord]) {',
  '                [void]$stderrLines.Add($_.Exception.Message)',
  '            } else {',
  '                [void]$stdoutLines.Add([string]$_)',
  '            }',
  '        }',
  '        $rc = $LASTEXITCODE',
  '    } catch {',
  '        [void]$stderrLines.Add($_.Exception.Message)',
  '    } finally {',
  '        [Console]::OutputEncoding = $prevEnc',
  '        $ErrorActionPreference = $prevEAP',
  '    }',
  '',
  '    Write-Host -NoNewline ("`r" + (\' \' * 40) + "`r")',
  '',
  '    if ($rc -eq 0) {',
  '        $result = ($stdoutLines -join "`n").TrimEnd()',
  '        if ($result) {',
  '            [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $result)',
  '        }',
  '    } else {',
  '        $errMsg = (($stderrLines + $stdoutLines) -join "`n").TrimEnd()',
  '        if ($errMsg) { Write-Host -ForegroundColor Yellow $errMsg }',
  '    }',
  '',
  '    [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()',
  '}',
  '# <<< WhatTheShell (wts) PowerShell integration <<<',
  '',
];

export const POWERSHELL_INIT_SCRIPT = LINES.join('\n');
