/**
 * PowerShell 集成脚本模板。
 *
 * 依赖 PSReadLine（Windows PowerShell 5.1 / PowerShell 7 默认预装）。
 * 通过 `Set-PSReadLineKeyHandler -Chord 'Ctrl+g'` 注册 Ctrl+G 处理函数。
 *
 * 输出脚本做了几件事提高兼容性：
 * 1. 所有注释和字符串都是 ASCII —— `Out-String | Add-Content -Path $PROFILE`
 *    在 PS 5.1 上会用系统 ANSI 写文件，中文经由 UTF8 → GBK 再读回 UTF-16 容易
 *    丢字节；纯 ASCII 就没这个风险。
 * 2. 不使用反引号续行 —— 反引号在 `Out-String` 的默认 `-Width 80` 截断下有风
 *    险，单行写完最稳。
 * 3. 调 wts 时用数组 splat；空 buffer 不传 --buffer，避免 PS 5.1 native 参数
 *    透传丢空串导致 commander 读不到 <description>。
 *
 * 安装路径：追加到 $PROFILE（通常 Documents/PowerShell/Microsoft.PowerShell_profile.ps1）。
 */
const LINES: string[] = [
  '# >>> WhatTheShell (wts) PowerShell integration >>>',
  '# Generated by: wts shell-init powershell',
  '',
  'if (-not (Get-Module -ListAvailable -Name PSReadLine)) {',
  "    Write-Warning 'WhatTheShell: PSReadLine not found, Ctrl+G integration skipped'",
  '    return',
  '}',
  '',
  "Set-PSReadLineKeyHandler -Chord 'Ctrl+g' -BriefDescription 'WhatTheShell inline' -Description 'Generate shell command via AI and fill the current buffer' -ScriptBlock {",
  "    $line = ''",
  '    $cursor = 0',
  '    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)',
  "    if ($null -eq $line) { $line = '' }",
  '',
  "    Write-Host ''",
  "    $intent = Read-Host -Prompt 'wts >'",
  '    if ([string]::IsNullOrWhiteSpace($intent)) {',
  '        [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()',
  '        return',
  '    }',
  '',
  "    Write-Host -NoNewline 'wts: thinking...'",
  '',
  '    $tmpout = [System.IO.Path]::GetTempFileName()',
  '    $tmperr = [System.IO.Path]::GetTempFileName()',
  '    $rc = 1',
  '    try {',
  "        $wtsArgs = [System.Collections.ArrayList]@('generate', '--inline')",
  '        if ($line.Length -gt 0) {',
  "            [void]$wtsArgs.Add('--buffer')",
  '            [void]$wtsArgs.Add($line)',
  '        }',
  "        [void]$wtsArgs.Add('--')",
  '        [void]$wtsArgs.Add($intent)',
  '        & wts @wtsArgs 1>$tmpout 2>$tmperr',
  '        $rc = $LASTEXITCODE',
  '    } catch {',
  '        $_ | Out-String | Set-Content -Path $tmperr',
  '    }',
  '',
  '    Write-Host -NoNewline ("`r" + (\' \' * 40) + "`r")',
  '',
  '    if ($rc -eq 0) {',
  '        $raw = Get-Content -Raw -Path $tmpout -ErrorAction SilentlyContinue',
  "        $result = if ($raw) { ([string]$raw).TrimEnd() } else { '' }",
  '        if ($result) {',
  '            [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $result)',
  '        }',
  '    } else {',
  '        $raw = Get-Content -Raw -Path $tmperr -ErrorAction SilentlyContinue',
  "        $errMsg = if ($raw) { ([string]$raw).TrimEnd() } else { '' }",
  '        if ($errMsg) { Write-Host -ForegroundColor Yellow $errMsg }',
  '    }',
  '',
  '    Remove-Item $tmpout, $tmperr -ErrorAction SilentlyContinue -Force',
  '    [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()',
  '}',
  '# <<< WhatTheShell (wts) PowerShell integration <<<',
  '',
];

export const POWERSHELL_INIT_SCRIPT = LINES.join('\n');
