/**
 * zsh integration script template.
 *
 * Binds Ctrl+G to a ZLE widget that hands the current BUFFER and the
 * user's intent to `wts generate --inline`, replacing BUFFER with the
 * returned command but never auto-executing.
 *
 * Built as an array of string lines (joined with \n) to avoid escaping
 * hell between JS template interpolation and zsh quoting.
 */
const LINES: string[] = [
  '# >>> WhatTheShell (wts) zsh integration >>>',
  '# Generated by: wts shell-init zsh',
  '# Install: append the following to ~/.zshrc',
  '#   eval "$(wts shell-init zsh)"',
  '',
  '__wts_inline_widget() {',
  '  emulate -L zsh',
  '  local current="$BUFFER"',
  '  local intent=""',
  '',
  '  print',
  "  print -n $'\\x1b[36m[WhatTheShell]\\x1b[0m > '",
  '  if ! IFS= read -r intent; then',
  '    zle reset-prompt',
  '    return 0',
  '  fi',
  '  if [[ -z "$intent" ]]; then',
  '    zle reset-prompt',
  '    return 0',
  '  fi',
  '',
  '  print -n $\'\\e[2Kwts: thinking...\\r\'',
  '',
  '  local tmpout tmperr rc',
  '  tmpout=$(mktemp 2>/dev/null) || { zle reset-prompt; return 1 }',
  '  tmperr=$(mktemp 2>/dev/null) || { rm -f "$tmpout"; zle reset-prompt; return 1 }',
  '',
  '  command wts generate --inline --shell zsh \\',
  '    --buffer "$current" \\',
  '    --history-file "${HISTFILE:-}" \\',
  '    -- "$intent" \\',
  '    >"$tmpout" 2>"$tmperr"',
  '  rc=$?',
  '',
  '  print -n $\'\\e[2K\\r\'',
  '',
  '  if (( rc == 0 )); then',
  '    BUFFER=$(<"$tmpout")',
  '    CURSOR=${#BUFFER}',
  '  else',
  '    print -r -- "$(<"$tmperr")" >&2',
  '    BUFFER="$current"',
  '    CURSOR=${#BUFFER}',
  '  fi',
  '',
  '  rm -f "$tmpout" "$tmperr"',
  '  zle reset-prompt',
  '}',
  '',
  'zle -N __wts_inline_widget',
  "bindkey '^G' __wts_inline_widget",
  '# <<< WhatTheShell (wts) zsh integration <<<',
  '',
];

export const ZSH_INIT_SCRIPT = LINES.join('\n');
